### ISSUE TITLE
Consider use consistent formatting tool 

### ISSUE THREAD

**Issue by George-Miao** [ATgump/rnd_website#4]
I'd recommend yapf or black, but autopep8 is also a good choice. For more info, see [pep8](https://peps.python.org/pep-0008/).

**Comment by avery-gump** [comment]
Thanks for the recommendations George, black seems like it requires a bit less setup than yapf so I went with this. Added it to the requirements.txt and the guide posted in files on the teams. I will use this myself from now on, sorry for making you do my cleanup this wont happen again!
